include:
  - board: nice_nano_v2
    shield: corne_left
    config: config/corne_left.keymap
    cmake-args: >
      -DCONFIG_ZMK_DISPLAY=y
      -DCONFIG_ZMK_RGB_UNDERGLOW=y
      -DCONFIG_WS2812_STRIP=y
    artifact-name: corne_left_rgb_oled

  - board: nice_nano_v2
    shield: corne_right
    config: config/corne_right.keymap
    cmake-args: >
      -DCONFIG_ZMK_DISPLAY=y
      -DCONFIG_ZMK_RGB_UNDERGLOW=y
      -DCONFIG_WS2812_STRIP=y
    artifact-name: corne_right_rgb_oled
